version: '3.9'

services:
  auth:
    build:
      context: .
      dockerfile: ./docker/auth.Dockerfile
    container_name: auth-service
    ports:
      - "3001:3000"
    env_file:
      - ./services/auth/.env
    depends_on:
      - nginx
    networks:
      - app-network

  oauth:
    build:
      context: .
      dockerfile: ./docker/oauth.Dockerfile # Updated path
    container_name: oauth-service
    ports:
      - "3002:3000"
    env_file:
      - ./services/oauth/.env
    depends_on:
      - nginx
    networks:
      - app-network

  files:
    build:
      context: .
      dockerfile: ./docker/files.Dockerfile # Updated path
    container_name: files-service
    ports:
      - "3003:3000"
    env_file:
      - ./services/files/.env
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    container_name: nginx-proxy
    environment:
      NGINX_PORT: 80
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
