version: '3.9'

services:
  auth:
    build:
      context: .
      dockerfile: ./docker/auth.Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth/.env
    volumes:
      - ./services/auth/.next:/var/www/auth/.next:ro
    depends_on:
      - nginx
    networks:
      - app-network

  cloudlink:
    build:
      context: .
      dockerfile: ./docker/cloudLink.Dockerfile # Updated path
    container_name: cloudLink-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/cloud_link/.env
    depends_on:
      - nginx
    networks:
      - app-network

  filenest:
    build:
      context: .
      dockerfile: ./docker/fileNest.Dockerfile # Updated path
    container_name: fileNest-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/file_nest/.env
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    container_name: nginx-proxy
    environment:
      NGINX_PORT: 80
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      app-network:
        aliases:
          - gateway

networks:
  app-network:
    driver: bridge
